Repository scientific-python/scientific-python.org, pull requests merged in 2024-09, with the labels that each got.

#668 Make SPEC draft status explicit
  layouts/partials/specs/spec_list.html
  layouts/partials/specs/spec_meta.html
Labels: Discuss in meeting

#666 Restyle SPEC table
  assets/css/custom.css
  layouts/partials/specs/spec_list.html
  layouts/partials/specs/spec_meta.html
Labels: enhancement, Discuss in meeting

#678 MAINT: Updated networkx calendar
  calendars/networkx.yaml
Labels: calendar
